# GitHub Action: whenever creating a new release of the source code,
# also create a release of the installable plugin.
# Steps to execute:
# - Checkout the source code
# - Run "composer install" to download all dependencies under vendor/
# - Create a .zip file, excluding:
#   - All hidden files (.git, .gitignore, etc)
#   - All development files, ending in .dist
#   - All composer files <= after installing dependencies, no need for them anymore
#   - Markdown files concerning development
#   - Folder build/ <= created only to store the .zip file
#   - Folder dev-helpers/ <= not needed for the plugin
# - Upload the .zip file as an artifact to the action (this step is possibly optional)
# - Upload the .zip file as a release, for download
name: Generate Installable Plugin, and Upload as Release Asset
on:
  release:
    types: [published]
jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: |
          composer install --no-dev --optimize-autoloader
          mkdir build
      - name: Create Zip
        run: |
          zip -r build/debug-log-reader.zip . \
          -x ".*" \
          -x "*/\.*" \
          -x "*.dist" \
          -x "composer.*" \
          -x "build/**" \
          -x "dev-helpers/**" \
          -x "CODE_OF_CONDUCT.md" \
          -x "CONTRIBUTING.md" \
          -x "ISSUE_TEMPLATE.md" \
          -x "PULL_REQUEST_TEMPLATE.md"
      - name: Upload to Release
        uses: svenstaro/upload-release-action@v2
        with:
          file: build/debug-log-reader.zip
          repo_token: ${{ secrets.RELEASE_PAT }}
          asset_name: debug-log-reader.zip
          tag: ${{ github.ref }}
          overwrite: true
